feat(sms): add example-generated task/servertemplate
FrangipaneTeam/provider-flexibleengine pull request #125
Opened 2023-01-17 15:34 UTC by valentin-dubreuil

### Description of your changes

I have:
add example generated 
waiting for the fix of the [creation of an AK/SK pair](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/issues/695) issue to do an example 
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

2023-01-17 17:19 UTC, azrod requested changes

2023-01-17 17:19 UTC, azrod commented on config/sms/config.go
> +		p.AddResourceConfigurator("flexibleengine_sms_server_template", func(r *config.Resource) {
Please lint block

2023-01-17 17:19 UTC, azrod commented on config/sms/config.go
> +				Type: tools.GenerateType("vpc", "Subnet"),
```suggestion
				Type: tools.GenerateType("vpc", "VPCSubnet"),
				Extractor: tools.GenerateExtractor(true, "id"),
```

2023-01-17 17:19 UTC, azrod commented on config/sms/config.go
> +				Type: tools.GenerateType("vpc", "Vpc"),
```suggestion
				Type: tools.GenerateType("vpc", "VPC"),
```

2023-01-19 10:56 UTC, azrod requested changes

2023-01-19 10:56 UTC, azrod commented on examples/sms/task.yaml
> +    testing.upbound.io/example-name: migration
Please respect conventional labelling 

`example_group_resource`

2023-01-19 10:56 UTC, azrod commented on examples/sms/task.yaml
> +    sourceServerId: ${var.source_server}
Use random UUID

2023-01-19 10:57 UTC, azrod commented
Please regenerate `list-tested.md`

2023-01-19 13:31 UTC, dmicheneau approved these changes

2023-01-19 13:33 UTC, azrod approved these changes

2023-01-19 13:33 UTC, merged